// ============================================================
// Anna.I — Shared z-ai-web-dev-sdk wrapper
// ============================================================
// Centralizes SDK initialization with proper error handling.
// On Railway, the SDK reads config from /etc/.z-ai-config,
// which is generated by entrypoint.sh from env vars:
//   Z_AI_BASE_URL, Z_AI_API_KEY (required)
//   Z_AI_CHAT_ID, Z_AI_USER_ID, Z_AI_TOKEN (optional)
//
// If the config is missing, AI features should gracefully degrade
// rather than crash with a cryptic error.
// ============================================================

import ZAI from "z-ai-web-dev-sdk";

let _zai: Awaited<ReturnType<typeof ZAI.create>> | null = null;
let _initError: string | null = null;

/**
 * Get or create the ZAI SDK instance.
 * Caches the instance after first successful creation.
 * If initialization fails, throws a clear, descriptive error.
 */
export async function getZAI() {
  if (_zai) return _zai;
  if (_initError) throw new Error(_initError);

  try {
    _zai = await ZAI.create();
    return _zai;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    _initError = `AI SDK not configured: ${msg}. Please set Z_AI_BASE_URL and Z_AI_API_KEY env vars on the deployment platform.`;
    throw new Error(_initError);
  }
}

/**
 * Check if AI features are available (SDK configured).
 * Returns true if the SDK is ready or potentially ready,
 * false if a previous initialization attempt failed.
 */
export function isAIReady(): boolean {
  return _initError === null;
}
